foreground           #e4eee7
background           #101a16
selection_foreground #102018
selection_background #75c99a
url_color            #95ddb1
cursor               #a9dfb9
cursor_text_color    #102018
color0  #1a2920
color8  #718879
color1  #db8580
color9  #ef9c97
color2  #75b985
color10 #95ddb1
color3  #c4a568
color11 #dfc487
color4  #6aaf94
color12 #95ddb1
color5  #ae91b7
color13 #c9add0
color6  #66b6ad
color14 #91d8ce
color7  #c0cec4
color15 #eef5f0
active_border_color   #75c99a
inactive_border_color #354c3f
tab_bar_background #17241e
active_tab_foreground #102018
active_tab_background #75c99a
inactive_tab_foreground #a9b9ad
inactive_tab_background #20372b