foreground           #263041
background           #f5f7fb
selection_foreground #263041
selection_background #bdeeff
url_color            #267b9f
cursor               #a84968
cursor_text_color    #ffffff
color0  #dfe5ed
color8  #697487
color1  #bd627a
color9  #a84968
color2  #4b8060
color10 #356d4d
color3  #927035
color11 #78591f
color4  #267b9f
color12 #176a91
color5  #a67b9d
color13 #805b79
color6  #327c84
color14 #23646d
color7  #424e60
color15 #263041
active_border_color   #55cdfc
inactive_border_color #c5d0dc
tab_bar_background #f5f7fb
active_tab_foreground #263041
active_tab_background #bdeeff
inactive_tab_foreground #697487
inactive_tab_background #e8edf4